[build]
  publish = "."

# CSP 헤더 설정 - Firebase + Kakao 통합 지원 (강제 적용)
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.gstatic.com https://www.gstatic.com/firebasejs https://cdn.tailwindcss.com https://developers.kakao.com https://t1.kakaocdn.net https://apis.google.com; style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://fonts.googleapis.com; img-src 'self' data: blob: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://firestore.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://firebasestorage.googleapis.com https://content-firebaseappcheck.googleapis.com https://www.googleapis.com https://*.firebaseio.com wss://*.firebaseio.com https://developers.kakao.com https://kapi.kakao.com https://kauth.kakao.com; frame-src 'self' https://www.google.com https://recaptcha.google.com; object-src 'none'; base-uri 'self'; form-action 'self'"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Netlify Functions 설정
[functions]
  directory = "netlify/functions"

# 환경변수 (실제 값은 Netlify 대시보드에서 설정)
[context.production.environment]
  FIREBASE_PROJECT_ID = "pricehunter-99a1b"
  FIREBASE_PRIVATE_KEY_ID = "your-private-key-id"
  FIREBASE_PRIVATE_KEY = "your-private-key"
  FIREBASE_CLIENT_EMAIL = "your-client-email"
  FIREBASE_CLIENT_ID = "your-client-id"
  GOOGLE_SHEETS_API_KEY = "your-google-sheets-api-key"

# 스케줄된 함수 설정 (매 30분마다 실행)
[[plugins]]
  package = "@netlify/plugin-scheduled-functions"

[plugins.inputs]
  schedule = "*/30 * * * *"
  function = "sync-data"